### ISSUE TITLE
Set default color to white?

### ISSUE THREAD

**Issue by mgibbs189** [Sphinxxxx/vanilla-picker-mini#1]
Hey @Sphinxxxx thanks again for this library. It's very well-written and I love it so far.

I'm using Vanilla Picker Mini on a text input. As seen on <a href="https://d.pr/i/S4qo16">this screenshot</a>, it defaults to that **blueish color** when the input is empty.

```js
                picker.onOpen = function(color) {
                    picker.setColor($input.value);
                };
```

I'm wondering (a) why that happens, and (b) if the default "empty" value could be white (#fff) or something instead?

**Comment by Sphinxxxx** [comment]
Hello! Yes, the default is that blue color, see
https://github.com/Sphinxxxx/vanilla-picker-mini/blob/f301a3260830e0d6120ad81bb89417b53f9a818e/src/js/picker.js#L365

To set your own default, either use the `color` option in the constructor, or call `setColor()` once you have a picker instance:

```js
var picker = new Picker({
    parent: ...,
    /* Option 1 */
    color: '#fff',
});
/* Option 2 */
picker.setColor('#fff');
```

**Comment by mgibbs189** [comment]
Thanks @Sphinxxxx - P.S. are you available for contract work?

**Comment by Sphinxxxx** [comment]
Yes I am :)  Feel free to send me an email (you should see the address on my profile page).
