### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by roeycohen** [Sphinxxxx/vanilla-picker-mini#2]
hi, it would be great if this package would get an npm package just like vanilla-picker.
after all... it takes almost half the size of vanilla-picker :)

**Comment by roeycohen** [comment]
it can also be good to export "Color" class, so that a user can validate his values manually.

**Comment by Sphinxxxx** [comment]
Thanks, v1.1.0 is now on NPM :)
The `Color` class is exposed through `Picker.Color`, i.e:

    var c = new Picker.Color('#345');

**Comment by roeycohen** [comment]
amazing! 10x :)
